"""add decisions table

Revision ID: 50f4ed5c31a0
Revises: 0fb4828fc200
Create Date: 2025-12-30 16:41:05.056854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f4ed5c31a0'
down_revision: Union[str, Sequence[str], None] = '0fb4828fc200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name='decision_status_check'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('study_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    # ### end Alembic commands ###
